spring:
  application:
    name: cicd-demo
  profiles:
    active: h2
  liquibase:
    enabled: true
    change-log: classpath:db/liquibase/changelog-demo.xml

mybatis:
  configuration:
    safe-result-handler-enabled: false
    aggressive-lazy-loading: false
    default-executor-type: reuse
    lazy-loading-enabled: true
  mapper-locations:
    - classpath*:mybatis/**/*Dao.xml